config/routes.rb
Rails.application.routes.draw do

  resources :event_location

  post 'event_location/create'

  resources :events do
   member do
    get 'fetch'
   end
   resources :orders, only: [:new, :create]
  end

  root 'event_location#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

  validates :event_location_id,
            :presence => true

  validates :name,
            :presence => true

  validates :ticket_price,
            :numericality => {:greater_than => 0}

  belongs_to :event_location
  has_many :orders, :dependent => :destroy
end

app/models/event_location.rb
class EventLocation < ActiveRecord::Base

  validates :name,
            :presence => true

  validates :available_seats,
            :numericality => {:greater_than => 0}

  has_many :events, :dependent => :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base

  validates :first_name,
            :presence => true

  validates :last_name,
            :presence => true

  validates :quantity,
            :numericality => {:greater_than => 0}

  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/event_location_controller.rb
class EventLocationController < ApplicationController
  def index
    @locations = EventLocation.order(:name).all
  end

  def show
    @location = EventLocation.find(params[:id])
    @events = @location.events
  end

  def new
    @location = EventLocation.new
  end

  def create
    @location = EventLocation.new(location_params)
    if @location.save
      redirect_to :action => 'index'
    else
      render 'new'
    end
  end

  def edit
    @location = EventLocation.find(params[:id])
  end

  def update
    @location = EventLocation.find(params[:id])
    if @location.update(location_params)
      redirect_to @location
    else
      render 'edit'
    end
  end

  def destroy
    @location = EventLocation.find(params[:id])
    @location.destroy
    redirect_to :action => 'index'
  end

  private

  def location_params
    params.require(:location).permit(:name, :available_seats, :description)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @event = Event.new
    @location_id = params[:id]
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event.id)
    else
      @location_id = params[:event][:event_location_id]
      render 'fetch'
    end
  end

  def show
    @event = Event.find(params[:id])
    @total_ticket = @event.event_location.available_seats
    @ticket_sold = Order.where('event_id =?', @event.id).sum(:quantity)
    @remaining_ticket = @total_ticket - @ticket_sold
    @location = @event.event_location
  end

  def edit
     @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to event_location_path(@event.event_location_id)
  end

  def fetch
    @event = Event.new
    @location_id = params[:id]
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :ticket_price, :event_location_id)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :load_eventable, only: [:create]

  def new
    @order = Order.new
  end

  def create
    @total_ticket = @event.event_location.available_seats
    @ticket_sold = Order.where('event_id =?', @event.id).sum(:quantity)
    @remaining_ticket = @total_ticket - @ticket_sold
    @order = Order.new(order_params)
    if @remaining_ticket >= params[:order][:quantity].to_i && @order.save
      redirect_to event_path(@order.event_id)
    else
      @error = "Please check remaining ticket"
      render 'new'
    end
  end

  private

  def order_params
    params.require(:order).permit(:first_name, :last_name, :quantity, :event_id)
  end

  def load_eventable
    @event = Event.find(params[:event_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/event_location_helper.rb
module EventLocationHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/event_location/edit.html.erb
<% @title = 'Edit Event Location'%>
<h2>Edit event location </h2>

<%= form_for :location, url: event_location_path(@location), method: :patch do |f| %>

    <% if @location.errors.any? %>
        <ul>
          <% @location.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>

    <p>
      <%= f.label :name %>
      <%=  f.text_field :name %>
    </p>

    <p>
      <%= f.label :available_seats %>
      <%= f.text_field(:available_seats) %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area(:description) %>
    </p>
    <p>
      <%= f.submit %>
    </p>

<% end %>
<p>
  <%= link_to 'Back to details', action: 'show' %>
</p>

app/views/event_location/index.html.erb
<% @title = 'Index Event Locations' %>

<h1>Event Locations</h1>
<h4>Choose your Event Location.</h4>
<ul>
  <% @locations.each do |location|%>
  <li><%= link_to  location.name, action: 'show', id: location.id %>
      </li>
      <% end %>
</ul>
<p>
  <%= link_to 'Create new event location', action: 'new' %>
</p>

app/views/event_location/new.html.erb
<% @title = 'New Event Location'%>
<h2>Create a new event location</h2>

<%= form_for :location, url: 'create' do |f| %>

    <% if @location.errors.any? %>
        <ul>
          <% @location.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>

  <p>
    <%= f.label :name %>
    <%=  f.text_field :name %>
  </p>

  <p>
    <%= f.label :available_seats %>
    <%= f.text_field :available_seats %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>
<p>
  <%= link_to 'Back to all event locations', action: 'index' %>
</p>

app/views/event_location/show.html.erb
<% @title = @location.name + ' details' %>
<h2><%= h @location.name %></h2>
<p>Description: <%= h @location.description %></p>
<p>Max. seats: <%= h @location.available_seats %></p>
<p>Total Events: <%= @location.events.count %></p>
<p>
  <%= link_to 'Edit', edit_event_location_path(params[:id]) %>
  <%= link_to 'Delete', event_location_path(@location), method: :delete, confirm: 'Are you sure?' %>
</p>
<p>
  All events at this location:
  <ul>
    <% @events.each do |event| %>
    <li>
      <%= link_to event.name, event_path(event) %>
    </li>
        <% end %>
  </ul>
</p>
<p>
  <%= link_to 'Create a new event', fetch_event_path(params[:id]) %>
</p>
<p><%= link_to 'Back to all event locations', action: 'index' %></p>

app/views/events/edit.html.erb
<% @title = 'Edit Event'%>
<h1>Edit event</h1>

<%= form_for @event do |f| %>
  <input type="hidden" id="event_location_id" name="event[event_location_id]" value="<%= @event.event_location_id %>"/>
    <% if @event.errors.any? %>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <p>
      <%= f.label :name %>
      <%=  f.text_field :name %>
    </p>

    <p>
      <%= f.label :ticket_price %>
      <%= f.text_field :ticket_price %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.submit %>
    </p>

<% end %>
<p>
  <%= link_to 'Back to event locations', event_location_path(@event.event_location_id) %>
</p>

app/views/events/fetch.html.erb
<% @title = 'New Event'%>
<h2>Create a new event</h2>



<%= form_for @event do |f| %>
  <input type="hidden" id="event_location_id" name="event[event_location_id]" value="<%= @location_id %>"/>
    <% if @event.errors.any? %>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>

    <p>
      <%= f.label :name %>
      <%=  f.text_field :name %>
    </p>

    <p>
      <%= f.label :ticket_price %>
      <%= f.text_field :ticket_price %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.submit %>
    </p>

<% end %>
<p>
  <%= link_to 'Back to event locations', event_location_path(@location_id) %>
</p>

app/views/events/show.html.erb
<% @title = @event.name + ' details' %>
<h2><%= h @event.name %></h2>
<p>Description: <%= h @event.description %></p>
<p>Ticket Price: <%= @event.ticket_price %></p>
<p>Ticket Sold: <%=  @ticket_sold %></p>
<p>Total Turn Over: <%=  @ticket_sold * @event.ticket_price %></p>
<p>Total Ticket: <%=  @total_ticket %></p>
<p>Remaining Ticket: <%=  @remaining_ticket %></p>
<% if @remaining_ticket > 0 %>
  <%= link_to 'Book ticket', new_event_order_path(@event) %>
<% else %>
  <%= link_to 'No ticket available', '#' %>
<% end %>

<p>
  <%= link_to 'Edit', :action =>  'edit', :id => @event.id %>
  <%= link_to 'Delete', event_path(@event), method: :delete, :confirm => 'Are you sure?' %>
</p>
<p><%= link_to 'Back to event location', event_location_path(@event.event_location_id) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineTicket - <%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1>Online Event Tickets</h1>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/orders/new.html.erb
<% @title = 'Ticket Booking'%>
<h2>Create a ticket booking</h2>

<%= form_for :order, :url => { :action => :create } do |f| %>
  <input type="hidden" name="order[event_id]" value="<%= params[:event_id] %>"/>
  <% if @error.present? %>
      <ul>
        <li><%= @error %></li>
      </ul>
  <% end %>

  <p>
    <%= f.label :first_name %>
    <%=  f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<p>
  <%= link_to 'Back to event', event_path(params[:event_id]) %>
</p>